CREATE TABLE talent
(
  id serial NOT NULL,
  createbyuserid bigint,
  createtimemillis bigint,
  lastupdatetimemillis bigint,
  updatebyuserid bigint,
  address character varying(255),
  coached boolean,
  country character varying(255),
  datebirth character varying(255),
  discoveryyears integer,
  email character varying(255),
  family character varying(255),
  familyincome bigint,
  firstname character varying(255),
  headline character varying(255),
  height double precision,
    independentscore integer,
  interestlevel character varying(255),
  lastname character varying(255),
  location character varying(255),
  maritalstatus character varying(255),
  middlename character varying(255),
phone character varying(255),
  placebirth character varying(255),
  rationalgutfeel character varying(255),
  relation character varying(255),
  relativerankamongtalents integer,
  schoolname character varying(255),
  schoolsuccesslvel character varying(255),
  skill character varying(255),
  socialaccount character varying(255),
  state character varying(255),
  status character varying(255),
  strength integer,
  talentgutfeel text,
  testimonies character varying(255),
  training character varying(255),
   weight character varying(255),
  workproduct character varying(255),
  workstatus character varying(255),
  traininghistory character varying(255),
 picturepath character varying(255),
  picturename character varying(255),
  address2 character varying(255),
city character varying(255),
  addressstate character varying(255),
zip character varying(255),
  sex character varying(255),
 scorefinal double precision,
 scorecategorytraits double precision,
scorepersonalitytraits double precision,
 scoreage double precision,
   scoretraining double precision,
   scorefamilyincome double precision,
scoregeographyincome double precision,
scoreevidence double precision,
  categoryid bigint,
completed boolean,
originaltalentid bigint,
  workproductfilename character varying(255),
  workproductfilepath character varying(255),
  CONSTRAINT talent_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE talent
  OWNER TO promytheus;